name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Static analysis
    uses: less-action/reusables/.github/workflows/pre-commit.yaml@v2
    with:
      python-version: "3.10"

  check-build:
    name: Check packaging metadata
    uses: less-action/reusables/.github/workflows/python-test-build.yaml@v2

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
          restore-keys: ${{ runner.os }}-pip
      - run: pip install -e '.[test]'
      - run: coverage run -m pytest
      - run: coverage report && coverage xml
      - name: Report coverage
        uses: codecov/codecov-action@v2
        with:
          file: coverage.xml
          fail_ci_if_error: true
          name: codecov-py${{ matrix.python-version }}
