name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    name: Static analysis
    uses: antonagestam/goose/.github/workflows/run.yaml@0.9.0

  check-build:
    name: Check packaging metadata
    uses: less-action/reusables/.github/workflows/python-test-build.yaml@v8

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.cfg
          check-latest: true
      - run: pip install -e '.[test]'
      - run: coverage run -m pytest
      - run: coverage report -m && coverage xml
      - uses: codecov/codecov-action@v5
        if: '!github.event.schedule'
        with:
          files: coverage.xml
          name: codecov-py${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
