name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    name: Static analysis
    uses: antonagestam/goose/.github/workflows/run.yaml@0.10.2

  check-build:
    name: Check packaging metadata
    uses: less-action/reusables/.github/workflows/python-test-build.yaml@v10

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml
          check-latest: true
          allow-prereleases: true
      - run: pip install -e '.[test]'
      - run: coverage run -m pytest
      - run: coverage report -m && coverage xml
      - uses: codecov/codecov-action@v5
        if: '!github.event.schedule'
        with:
          files: coverage.xml
          name: codecov-py${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  type-check:
    name: Type check
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
      COLUMNS: "150"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: pip
          cache-dependency-path: requirements-typing.txt
          check-latest: true
      - name: mypy cache
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: "${{ runner.os }}-mypy-3.13-${{ hashFiles('requirements-typing.txt') }}"
          restore-keys: |
            ${{ runner.os }}-mypy-3.13
            ${{ runner.os }}-mypy
      - run: pip install -e .
      - run: pip install -r requirements-typing.txt
      - run: mypy --strict
