name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9.0-alpha - 3.9.0']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip
      - run: pip install -e .[test,lint]
      - name: mypy cache
        uses: actions/cache@v2
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-mypy-${{ hashFiles('setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-mypy
      - run: make lint
      - run: make test
